export class Country {
    constructor(
          public name?: {common?: string, official?:string},
          public tld?: string[],
          public cca2?: string,
          public ccn3?: string,
          public cca3?: string,
          public cioc?: string,
          public independent?: boolean,
          public status?: string,
          public unMember?: boolean,
          public currencies?: {},
          public idd?: {},
          public capital?: string[],
          public altSpellings?: string[],
          public region?: string,
          public subregion?: string,
          public languages?: {},
          public translations?: {},
          public latlng?: number[],
          public landlocked?: boolean,
          public borders?: string[],
          public area?: number,
          public demonyms?: {},
          public flags?: {png:string, svg:string},
          public maps?: {},
          public population?: number,
          public gini?: {},
          public fifa?: string,
          public car?: {},
          public timezones?: string[],
          public continents?: string[],
          public coatOfArms?: {},
          public startOfWeek?: string,
          public capitalInfo?: {},
          public postalCode?: {}
    ){}
}
